================================================================================
SENSOR PIPELINE - GOLD LAYER
================================================================================

-- Create Gold enriched table
CREATE OR REPLACE TABLE A_database.T_SCH.GOLD_SENSOR_METRICS (
    READING_ID          VARCHAR,
    SENSOR_ID           VARCHAR     NOT NULL,
    READING_TIMESTAMP   TIMESTAMP_NTZ NOT NULL,
    READING_DATE        DATE,
    READING_HOUR        NUMBER,
    VOLTAGE             FLOAT,
    CURRENT_AMP         FLOAT,
    POWER_WATTS         FLOAT,
    ENERGY_KWH          FLOAT,
    POWER_FACTOR        FLOAT,
    FREQUENCY_HZ        FLOAT,
    LOCATION            VARCHAR,
    METER_TYPE          VARCHAR,
    IS_VOLTAGE_ANOMALY  BOOLEAN,
    IS_CURRENT_ANOMALY  BOOLEAN,
    IS_POWER_FACTOR_ANOMALY BOOLEAN,
    IS_ANOMALY          BOOLEAN,
    ANOMALY_REASON      VARCHAR,
    ENRICHED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create chained task: Silver stream -> Gold
CREATE OR REPLACE TASK A_database.T_SCH.TASK_SILVER_TO_GOLD
  WAREHOUSE = COMPUTE_WH
  AFTER A_database.T_SCH.TASK_BRONZE_TO_SILVER
AS
INSERT INTO A_database.T_SCH.GOLD_SENSOR_METRICS (
    READING_ID, SENSOR_ID, READING_TIMESTAMP, READING_DATE, READING_HOUR,
    VOLTAGE, CURRENT_AMP, POWER_WATTS, ENERGY_KWH, POWER_FACTOR, FREQUENCY_HZ,
    LOCATION, METER_TYPE,
    IS_VOLTAGE_ANOMALY, IS_CURRENT_ANOMALY, IS_POWER_FACTOR_ANOMALY,
    IS_ANOMALY, ANOMALY_REASON
)
SELECT
    READING_ID,
    SENSOR_ID,
    READING_TIMESTAMP,
    DATE_TRUNC('DAY', READING_TIMESTAMP)::DATE,
    HOUR(READING_TIMESTAMP),
    VOLTAGE,
    CURRENT_AMP,
    POWER_WATTS,
    ENERGY_KWH,
    POWER_FACTOR,
    FREQUENCY_HZ,
    LOCATION,
    METER_TYPE,
    CASE WHEN VOLTAGE < 200 OR VOLTAGE > 250 THEN TRUE ELSE FALSE END,
    CASE WHEN CURRENT_AMP < 0 OR CURRENT_AMP > 15 THEN TRUE ELSE FALSE END,
    CASE WHEN POWER_FACTOR < 0.7 THEN TRUE ELSE FALSE END,
    CASE WHEN VOLTAGE < 200 OR VOLTAGE > 250 OR CURRENT_AMP < 0 OR CURRENT_AMP > 15 OR POWER_FACTOR < 0.7 THEN TRUE ELSE FALSE END,
    TRIM(
        CASE WHEN VOLTAGE < 200 OR VOLTAGE > 250 THEN 'VOLTAGE_OUT_OF_RANGE; ' ELSE '' END ||
        CASE WHEN CURRENT_AMP < 0 OR CURRENT_AMP > 15 THEN 'CURRENT_OUT_OF_RANGE; ' ELSE '' END ||
        CASE WHEN POWER_FACTOR < 0.7 THEN 'LOW_POWER_FACTOR; ' ELSE '' END,
        '; '
    )
FROM A_database.T_SCH.SILVER_SENSOR_STREAM;

-- Initial load
INSERT INTO A_database.T_SCH.GOLD_SENSOR_METRICS (
    READING_ID, SENSOR_ID, READING_TIMESTAMP, READING_DATE, READING_HOUR,
    VOLTAGE, CURRENT_AMP, POWER_WATTS, ENERGY_KWH, POWER_FACTOR, FREQUENCY_HZ,
    LOCATION, METER_TYPE,
    IS_VOLTAGE_ANOMALY, IS_CURRENT_ANOMALY, IS_POWER_FACTOR_ANOMALY,
    IS_ANOMALY, ANOMALY_REASON
)
SELECT
    READING_ID, SENSOR_ID, READING_TIMESTAMP,
    DATE_TRUNC('DAY', READING_TIMESTAMP)::DATE,
    HOUR(READING_TIMESTAMP),
    VOLTAGE, CURRENT_AMP, POWER_WATTS, ENERGY_KWH, POWER_FACTOR, FREQUENCY_HZ,
    LOCATION, METER_TYPE,
    CASE WHEN VOLTAGE < 200 OR VOLTAGE > 250 THEN TRUE ELSE FALSE END,
    CASE WHEN CURRENT_AMP < 0 OR CURRENT_AMP > 15 THEN TRUE ELSE FALSE END,
    CASE WHEN POWER_FACTOR < 0.7 THEN TRUE ELSE FALSE END,
    CASE WHEN VOLTAGE < 200 OR VOLTAGE > 250 OR CURRENT_AMP < 0 OR CURRENT_AMP > 15 OR POWER_FACTOR < 0.7 THEN TRUE ELSE FALSE END,
    TRIM(
        CASE WHEN VOLTAGE < 200 OR VOLTAGE > 250 THEN 'VOLTAGE_OUT_OF_RANGE; ' ELSE '' END ||
        CASE WHEN CURRENT_AMP < 0 OR CURRENT_AMP > 15 THEN 'CURRENT_OUT_OF_RANGE; ' ELSE '' END ||
        CASE WHEN POWER_FACTOR < 0.7 THEN 'LOW_POWER_FACTOR; ' ELSE '' END,
        '; '
    )
FROM A_database.T_SCH.SILVER_SENSOR_READINGS;
-- Result: 2,500 rows inserted, 104 anomalies (4.16%)

-- Resume tasks (child first, then root)
ALTER TASK A_database.T_SCH.TASK_SILVER_TO_GOLD RESUME;
ALTER TASK A_database.T_SCH.TASK_BRONZE_TO_SILVER RESUME;